name: ls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    # Rest of your steps...

    - name: List dataset directory contents
      run: dir .\Battery-State-of-Charge-Estimation\dataset\
      shell: pwsh


