name: Python Package using Python and Pip on Windows with Jupyter Notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-dependencies:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

<<<<<<< HEAD
    - name: Cache pip and Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/AppData/Local/pip/Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: cmd

  execute-dnn-notebook:
    needs: setup-dependencies
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Restore pip cache
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/AppData/Local/pip/Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: cmd

    - name: Execute Jupyter Notebook (DNN)
      run: |
        python -m jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=-1 --to notebook --execute modeling_and_evaluation/SOC_Estimation_DNN.ipynb --output executed_dnn_notebook.ipynb
      shell: cmd

  execute-lstm-notebook:
    needs: setup-dependencies
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Restore pip cache
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/AppData/Local/pip/Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: cmd

    - name: Execute Jupyter Notebook (LSTM)
      run: |
        python -m jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=-1 --to notebook --execute modeling_and_evaluation/SOC_Estimation_LSTM.ipynb --output executed_lstm_notebook.ipynb
      shell: cmd
=======
    # - name: Install Dependencies with Pip
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #     pip install jupyter nbconvert
    #     pip install pytest
    #   shell: cmd

    # - name: Print Working Directory
    #   run: echo %CD%
    #   shell: cmd

    # - name: List Contents of the Project Directory
    #   run: dir
    #   shell: cmd

    # - name: List Contents of Dataset Directory
    #   run: dir dataset
    #   shell: cmd


    # - name: Execute DNN Training Notebook (Skip Training)
    #   env:
    #     SKIP_TRAINING: "True"
    #     SKIP_OPTUNA: "True"
    #   run: |
    #     jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=-1 --to notebook --execute modeling_and_evaluation/SOC_Estimation_DNN.ipynb --output modeling_and_evaluation/executed_dnn_notebook.ipynb
    #   shell: cmd

    # - name: Execute LSTM Training Notebook (Skip Training)
    #   env:
    #     SKIP_TRAINING: "True"
    #     SKIP_OPTUNA: "True"
    #   run: |
    #     jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=-1 --to notebook --execute modeling_and_evaluation/SOC_Estimation_LSTM.ipynb --output modeling_and_evaluation/executed_lstm_notebook.ipynb
    #   shell: cmd

    # - name: Run Tests with pytest
    #   run: pytest
    #   shell: cmd
>>>>>>> d5e61222bb436fd836e78db4578e5baa43263d49
